# Generated by Django 5.0.6 on 2026-09-19 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, help_text='Optional topic or title (e.g. Python Challenge #12)', max_length=200)),
                ('question', models.TextField(help_text='The daily quiz question or poll prompt')),
                ('explanation', models.TextField(help_text='Detailed explanation of the correct answer, shown after student votes')),
                ('points', models.PositiveIntegerField(default=10, help_text='Points awarded for a correct answer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Quiz',
                'verbose_name_plural': 'Daily Quizzes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this is the correct answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.dailyquiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.dailyquiz')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quizoption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'quiz'), name='unique_student_daily_quiz_submission'),
        ),
    ]
